---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lzy.
--- DateTime: 2024/7/2 16:24
---

package.cpath = package.cpath .. ';C:/Users/lzy/AppData/Roaming/JetBrains/Rider2023.2/plugins/EmmyLua/debugger/emmy/windows/x64/?.dll'
local dbg = require('emmy_core')
dbg.tcpConnect('localhost', 9966)